[theme]
base="light"
primaryColor="#FF9900"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F9F9F9"
textColor="#222222"
font="sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
